function y = doFilter(x,yFs)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.8 and DSP System Toolbox 9.10.
% Generated on: 30-Mar-2022 16:01:35

persistent Hd;

if isempty(Hd)
    
    Fpass = 1000;     % Passband Frequency
    Fstop = 5000;     % Stopband Frequency
    Apass = 1;        % Passband Ripple (dB)
    Astop = 40;       % Stopband Attenuation (dB)
    Fs    = yFs;  % Sampling Frequency
    
    h = fdesign.lowpass('fp,fst,ap,ast', Fpass, Fstop, Apass, Astop, Fs);
    
    Hd = design(h, 'equiripple', ...
        'MinOrder', 'any', ...
        'StopbandShape', 'flat');
    
    
    
    set(Hd,'PersistentMemory',true);
    
end

y = filter(Hd,x);

